export const ADD_COMPLAINT = 'ADD_COMPLAINT';
export const ADD_COMPLAINTS = 'ADD_COMPLAINTS';

export const OVERWRITE_COMPLAINTS = 'OVERWRITE_COMPLAINTS';

export const REMOVE_COMPLAINT = 'REMOVE_COMPLAINT';

export const READ_COMPLAINT = 'READ_COMPLAINT';
export const UNREAD_COMPLAINT = 'UNREAD_COMPLAINT';
